[tool.poetry]
name = "awesomeresume"
version = "0.1.0"
description = ""
authors = ["Boris"]

[tool.poetry.dependencies]
python = "^3.8"
Markdown = "^3.3.6"
pdfkit = "^1.0.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
